# action.yml
name: "Simple Slack Message"
description: "Send a simple slack message to a channel using incoming webhook for slack bot"
author: "Thim Lohse"
branding:
  icon: "message-square"
  color: "purple"
inputs:
  send-data:
    description: "data to send"
    required: true
    default: "Hello, World!"
  slack-hook-url:
    description: "slack hook url"
    required: true
outputs:
  success:
    description: "If the message was successfully sent. true/false"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.send-data }}
    - ${{ inputs.slack-hook-url }}
