# action.yml
name: "Simple Slack Message"
description: "Send a simple slack message to a channel"
inputs:
  send-data:
    description: "data to send"
    required: true
    default: "Hello, World!"
  slack-hook-url:
    description: "slack hook url"
    required: true
    default: "https://hooks.slack.com/services/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"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.send-data }
    - ${{ inputs.slack-hook-url }}
