on: [push]

jobs:
  simple_slack_message_job:
    runs-on: ubuntu-20.04
    name: A job to publish a message in slack for free
    steps:
      - name: Publish message step
        id: message
        uses: caesariab/simple-slack-message-action@v2.0.1
        with:
          slack-hook-url: ""
          send-data: "Jalla, habibi"
      - name: Get the output success status
        if: ${{ steps.message.outputs.success_status }}
        run: echo "Posting message successful"
