on: [push]

jobs:
  simple_slack_message_job:
    runs-on: ubuntu-latest
    name: A job to publish a message in slack for free
    steps:
      - name: Publish message step
        uses: caesariab/simple-slack-message-action@v1.2.0
        with:
          slack-hook-url: "https://hooks.slack.com/services/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"
          send-data: "Jalla, habibi"
