on: [push]

jobs:
  simple_slack_message_job:
    runs-on: ubuntu-latest
    name: A job to publish a message in slack for free
    steps:
      - name: Publish message step
        id: message
        uses: caesariab/simple-slack-message-action@v1.5.2
        with:
          slack-hook-url: ${{ secrets.SLACK_HOOK_URL }}
          send-data: "Jalla, habibi"
      - name: Get the output success status
        if: ${{ steps.message.outputs.success }}
        run: echo "Success"
      - name: "Second output"
        run: echo ${{ steps.message.outputs.action_fruit }}
